### ISSUE TITLE
Collections API antwortet mit HTTP:500

### ISSUE THREAD

**Issue by Philippluca** [GeoWerkstatt/geopilot#284]
**Steps to reproduce**
1. Go to 'app.geopilot.ch'
2. Login as any Admin
3. Go to STAC Browser

**Expected behavior**
STAC Browser shows list of mandates

**Current behavior**
Request to https://app.geopilot.ch/api/stac/collections returns HTTP:500

**Screenshots**
![image](https://github.com/user-attachments/assets/f4b4eea0-4f4c-41ae-9c96-3cd57b786828)

**Comment by domi-b** [comment]
Dieser Fehler tritt auf, wenn bei einem Mandat ein leerer SpatialExtent definiert ist, da STAC Collections immer einen Extent benötigen. (Beim Bearbeiten vom Extent gibt es aktuell auch noch Issue #281)

@Philippluca Sollen wir bei Mandaten den Extent als Pflichtfeld definieren oder für STAC in diesen Fällen einen Fallback-Extent (z.B. ganze Schweiz) verwenden?

**Comment by Philippluca** [comment]
@domi-b Ich denke wir sollten den Extent als Pflichtfeld deklarieren. Von den Administratoren können wir dies verlangen.
