### ISSUE TITLE
Beschreibung für STAC Collections und STAC Items

### ISSUE THREAD

**Issue by tschumpr** [GeoWerkstatt/geopilot#57]
Der STAC Browser zeigt standardmässig eine Beschreibung für Collections (Operate) und Items (Datenabgabe) an. Diese Beschreibungen wurden bisher für geocop nicht vorgesehen, weshalb vorerst ein leerer String als Beschreibung für die STAC Objekte gesetzt wird. 

Frage: Soll eine Beschreibung gesetzt werden? Was ist der Inhalt (zb etwas generiertes mit Modell, etc.)?

![Screenshot 2023-11-07 140343](https://github.com/GeoWerkstatt/geocop/assets/108136714/06093e59-29ea-48f1-9b42-d00b0f54d4e6)
![Screenshot 2023-11-07 140403](https://github.com/GeoWerkstatt/geocop/assets/108136714/7dbeef96-9858-4731-8b0b-168733390081)

**Comment by urs-g** [comment]
Für uns als Admin wäre es hilfreich, den Kommentar zu sehen, sowohl im STAC Browser als auch in der Abgabeübersicht (upload.geo.sh.ch/admin).
